# Generated by Django 4.2.1 on 2023-10-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('fono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=70)),
            ],
        ),
    ]
